#!/bin/zsh

defaults write http://com.apple.dock autohide-delay -float 0 && defaults write http://com.apple.dock autohide-time-modifier -float 0.2 && killall Dock
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.screencaptureui "thumbnailExpiration" -float 60
