git:
  overrideGpg: true
  autoFetch: false
  paging:
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 8 # out of 10

customCommands:
  - key: "F"
    context: "remotes"
    description: "Fetch + prune"
    command: "git fetch --prune {{.SelectedRemote.Name}}"
    output: log
    loadingText: "Fetching & pruning…"
