[Personal]
from = Robert Craigie <robert@craigie.dev>
source = imaps://robert%40craigie.dev@imap.gmail.com:993
source-cred-cmd = secret-tool lookup service aerc account personal
outgoing = smtps://robert%40craigie.dev@smtp.gmail.com:465
outgoing-cred-cmd = secret-tool lookup service aerc account personal
copy-to = [Gmail]/Sent Mail
archive = [Gmail]/All Mail
cache-headers = true
cache-max-age = 2160h
keepalive-period = 60s
check-mail = 5m
folders-sort = INBOX,[Gmail]/Sent Mail,[Gmail]/Drafts,[Gmail]/All Mail,[Gmail]/Starred,[Gmail]/Spam,[Gmail]/Trash
