[general]
unsafe-accounts-conf = true

[ui]
threading-enabled = true
sidebar-width = 24
mouse-enabled = true
timestamp-format = 2006-01-02 15:04
this-day-time-format = 15:04

[viewer]
pager = less -R

[compose]
editor = nvim
